version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: carteira-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: carteira
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: carteira_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 